name: "Get Unity version and changeset"
description: "Returns Unity version and changeset based on project path"
author: "Ivan Murashka"
inputs:
  project_path:
    description: Path to Unity project. Used to find Unity version
    required: true
    default: ${{ github.workspace }}
  version_env:
    description: The name of environment variable to store the version. Keep empty if you don't want to store it.
    required: false
    default: ""
  changeset_env:
    description: The name of environment variable to store the changeset. Keep empty if you don't want to store it.
    required: false
    default: ""
outputs:
  version:
    description: Unity version.
  changeset:
    description: Unity version changeset.
runs:
  using: "node12"
  main: "scripts/index.js"
branding:
  icon: box
  color: gray-dark
